using DeepPurge.Core.Schedule;
using System.Reflection;
using System.Runtime.ExceptionServices;
using Xunit;

namespace DeepPurge.Tests;

/// <summary>
/// Exercise the name sanitiser — injection of schtasks metacharacters
/// through the job name was part of the v0.9 hardening pass.
/// </summary>
public class ScheduleManagerTests
{
    // SanitizeName is private; reach it by reflection because the contract
    // is security-critical and worth locking in.
    private static string Sanitize(string input)
    {
        var mi = typeof(ScheduleManager).GetMethod(
            "SanitizeName",
            BindingFlags.NonPublic | BindingFlags.Static)!;
        return (string)mi.Invoke(null, new object[] { input })!;
    }

    private static string BuildWrapperScript(string cliPath, string? cliArgs)
    {
        var mi = typeof(ScheduleManager).GetMethod(
            "BuildWrapperScript",
            BindingFlags.NonPublic | BindingFlags.Static)!;

        try
        {
            return (string)mi.Invoke(null, new object?[] { cliPath, cliArgs })!;
        }
        catch (TargetInvocationException ex) when (ex.InnerException is not null)
        {
            ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
            throw;
        }
    }

    [Theory]
    [InlineData("Normal Job Name",      "Normal Job Name")]
    [InlineData("with_underscore-dash", "with_underscore-dash")]
    [InlineData("Nightly 3am",          "Nightly 3am")]
    public void Allows_normal_names(string input, string expected)
    {
        Assert.Equal(expected, Sanitize(input));
    }

    [Theory]
    [InlineData("foo & del /q *",             "foo  del q")]   // & / * stripped, trailing spaces trimmed
    [InlineData("job | rm -rf /",             "job  rm -rf")]
    [InlineData("a\"b\"c",                    "abc")]
    [InlineData("..\\..\\escape",             "escape")]
    [InlineData("'; DROP TABLE jobs; --",     "DROP TABLE jobs --")]
    [InlineData("",                           "DeepPurgeJob")]
    [InlineData("   ",                        "DeepPurgeJob")]
    public void Strips_metacharacters_and_falls_back(string input, string expected)
    {
        Assert.Equal(expected, Sanitize(input));
    }

    [Fact]
    public void Null_input_falls_back_to_default()
    {
        Assert.Equal("DeepPurgeJob", Sanitize(null!));
    }

    [Fact]
    public void Caps_at_64_chars()
    {
        var longName = new string('A', 200);
        var result = Sanitize(longName);
        Assert.Equal(64, result.Length);
    }

    [Fact]
    public void Wrapper_script_normalizes_safe_arguments()
    {
        var script = BuildWrapperScript(@"C:\Tools\DeepPurgeCli.exe", "  clean\tjunk   evidence --dry-run  ");

        Assert.Equal(
            "@echo off\r\n" +
            "setlocal DisableDelayedExpansion\r\n" +
            "REM DeepPurge scheduled job - regenerated by ScheduleManager.\r\n" +
            "\"C:\\Tools\\DeepPurgeCli.exe\" clean junk evidence --dry-run\r\n" +
            "exit /b %ERRORLEVEL%\r\n",
            script);
    }

    [Fact]
    public void Wrapper_script_allows_empty_arguments_without_shell_suffix()
    {
        var script = BuildWrapperScript(@"C:\Tools\DeepPurgeCli.exe", "   ");

        Assert.Contains("\"C:\\Tools\\DeepPurgeCli.exe\"\r\n", script);
        Assert.DoesNotContain("\"C:\\Tools\\DeepPurgeCli.exe\" ", script);
    }

    [Theory]
    [InlineData("clean junk & calc")]
    [InlineData("clean junk | calc")]
    [InlineData("clean junk < payload.txt")]
    [InlineData("clean junk > payload.txt")]
    [InlineData("clean junk ^& calc")]
    [InlineData("clean junk %PATH%")]
    [InlineData("clean junk !TEMP!")]
    [InlineData("clean \"junk\" evidence")]
    [InlineData("clean junk\r\ncalc")]
    [InlineData("clean junk (calc)")]
    public void Wrapper_script_rejects_batch_metacharacters(string cliArgs)
    {
        var ex = Assert.Throws<ArgumentException>(
            () => BuildWrapperScript(@"C:\Tools\DeepPurgeCli.exe", cliArgs));

        Assert.Contains("cmd.exe metacharacters", ex.Message);
    }
}
